// Generated by https://quicktype.io

export interface Enter {
  flags: Flags;
  name: Name;
  capital: string[];
}
export interface CountryMap {
  valid: boolean;
  countryName: string;
  capital?: string;
  flag: string;
  flagAlt: string;
  commonName: string;
}

export interface Option {
  options: CountryMap[];
  checkFor: string;
}

export interface ContextState {
  completed: boolean;
  currentQuestion: number;
  correctAnswers: number;
}

export interface Flags {
  png: string;
  svg: string;
  alt: string;
}

export interface Name {
  common: string;
  official: string;
  nativeName: { [key: string]: NativeName };
}

export interface NativeName {
  official: string;
  common: string;
}
